default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: forum_app
  password: 1234yong

development:
  <<: *default
  database: forum_app_development
  host: localhost


test:
  <<: *default
  database: forum_app_test

production:
  <<: *default
  database: forum_app_production
  username: forum_app_username
  password: 1234yong 
